### ISSUE TITLE
Why is biometric authentication a threat to the security of the user ?

### ISSUE THREAD

**Issue by Smile85363** [keshav-space/safenotes#120]
This is written in the section on enabling biometric authentication

**Comment by keshav-space** [comment]
> This is written in the section on enabling biometric authentication

See this discussion  https://github.com/keshav-space/safenotes/issues/57#issuecomment-1295832424

**Comment by keshav-space** [comment]
@Smile85363 should you need any further clarification please feel free to ask here..

**Comment by keshav-space** [comment]
Closing this, please feel free to reopen if you have any other queries.
