### ISSUE TITLE
The translation in Russian is poorly done

### ISSUE THREAD

**Issue by Smile85363** [keshav-space/safenotes#122]

**Comment by keshav-space** [comment]
The v2.2.0 release doesn't contain some of the translation refinements made by @TheDarkKRONOS after the release was finalized.

Those refinements would reflect in the next release.

In the meantime, if you want you can review the Russian translation 

- https://github.com/keshav-space/safenotes/blob/main/assets/translations/ru.json 
 OR
- https://hosted.weblate.org/translate/safe-notes/safe-notes-app/ru/


Feel free to suggest corrections/modifications.

**Comment by keshav-space** [comment]
Closing: Fixed in https://github.com/keshav-space/safenotes/pull/126 by @TheDarkKRONOS
