### ISSUE TITLE
Passphrase 

### ISSUE THREAD

**Issue by benbond88** [keshav-space/safenotes#123]
I forgot my passphrase and am hoping to recover or reset because I have some important information I need to recover from the app. Thank you for any help you may be able to give to me

**Comment by keshav-space** [comment]
> I forgot my passphrase and am hoping to recover or reset because I have some important information I need to recover from the app. Thank you for any help you may be able to give to me

@benbond88 Sorry, but It's not possible to decrypt notes without the passphrase, and that's what makes Safe Notes secure. The passphrase is the only key to your notes there is no way around it.
