### ISSUE TITLE
Enable and then disable Biometric 

### ISSUE THREAD

**Issue by debasen** [keshav-space/safenotes#134]
**Is your feature request related to a problem? Please describe.**
I understand the problem of enabling biometric. But if it is enabled and then disabled later is it still a threat? I mean will my passphrase still be saved in the app? Or I will be good as fresh installation?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by keshav-space** [comment]
> I understand the problem of enabling biometric. But if it is enabled and then disabled later is it still a threat? I mean will my passphrase still be saved in the app? Or I will be good as fresh installation?

As soon as you disable biometric authentication, the passphrase gets purged from storage.

https://github.com/keshav-space/safenotes/blob/9f938b18ad6b5c0094c63b7f35e1b749dae11298/lib/models/biometric_auth.dart#L21-L29

**Comment by debasen** [comment]
Oh, great! Any reason to first override the value and then delete it?

**Comment by keshav-space** [comment]
> Oh, great! Any reason to first override the value and then delete it?

That's an additional safeguard measure. It never hurts to be more cautious.

**Comment by keshav-space** [comment]
@debasen  closing this now. Hope you got your answer.
From next time, if you have any queries, please open a Q&A discussion here https://github.com/keshav-space/safenotes/discussions/new?category=q-a
