### ISSUE TITLE
Which branch or tag should I merge for stable updates?

### ISSUE THREAD

**Issue by monospare** [keshav-space/safenotes#150]
Hello, SafeNotes maintainers and contributors!

I'm interested in updating my fork of the SafeNotes repository and want to make sure I'm merging with the most stable branch or tag. Could you please provide guidance on which branch or tag I should merge with to ensure a stable experience?

Here's what I'm looking for:

The branch or tag name that represents the most recent stable release.
Any specific instructions or recommendations for merging, if applicable.
If there's a recommended method for staying updated on future stable releases, please let me know.
Thank you for your time and for your work on this project. I'm looking forward to contributing and staying up-to-date with SafeNotes' development.

**Comment by keshav-space** [comment]
The main branch is constantly under development. 
For stable updates, use the latest tag currently, https://github.com/keshav-space/safenotes/tree/v2.3.0.
