### ISSUE TITLE
BIG question

### ISSUE THREAD

**Issue by inKdahood** [keshav-space/safenotes#170]
Hello,
First thanks for your work =)
And second forgive my english its not my language.

Is there a way to open a safenotes on a pc ? On linux and windows ? 
I write a lot in this app and sometimes when i have a link or a text i need to open on my pc i actually copy paste to a txt file and pass the file to my pc but u know... im "paranoiac" and u know... my pc spy on me xD i will prefer if i can send the crypted backup json file from safenotes directly to my pc and open it on my pc is this possible ? 
If not its probably a big ask but can you please add this feature in first time on windows and in a second time on linux (in this order because windows spy more than linux =) 
Its not a obligation to have the possibility to edit it on pc (for me) only open it to see the text and be copyable will be REALLY nice.
Thanks for reading hope you will respond with good news.

**Comment by keshav-space** [comment]
@inKdahood  We already discussing this here https://github.com/keshav-space/safenotes/issues/51

**Comment by keshav-space** [comment]
Closing this in favor of https://github.com/keshav-space/safenotes/issues/51
