### ISSUE TITLE
[FEATURE REQUEST] Make password reminder optional

### ISSUE THREAD

**Issue by HarriBuh** [keshav-space/safenotes#174]
**Is your feature request related to a problem? Please describe.** + **Describe the solution you'd like**

It's very annoying for me to always enter my PW after ~10 successful logins. It should be optional, because I want to decide myself whether I want this kind of help/ reminder or not.

**Comment by keshav-space** [comment]
@HarriBuh  We already discussing this here https://github.com/keshav-space/safenotes/issues/159#issuecomment-1620637654

**Comment by keshav-space** [comment]
Closing this in favor of https://github.com/keshav-space/safenotes/issues/159
