### ISSUE TITLE
Add verification info (signing certificate for APK) on github

### ISSUE THREAD

**Issue by mollyuser** [keshav-space/safenotes#181]

**Comment by keshav-space** [comment]
Thanks @mollyuser, all the GitHub [release](https://github.com/keshav-space/safenotes/releases) now includes the SHA-256 digest of signing certificate.

To verify download the safenotes apk from GitHub release and use `apksigner --print-certs <path-to-apk-file>` to get the SHA256 digest of the certificate.
The SHA-256 digest of the signing certificate should be `0a63d47a2afcf09dcf1a408ff36f6c71950a066532241538bdd97dc588811b50`, as shown in the example below.

```yaml
❯ apksigner verify --print-certs safenotes-2.3.0-all.apk
Signer #1 certificate DN: CN=Safe Notes, OU=Unknown, O=Trisven Networks, L=Unknown, ST=Unknown, C=Unknown
Signer #1 certificate SHA-256 digest: 0a63d47a2afcf09dcf1a408ff36f6c71950a066532241538bdd97dc588811b50
Signer #1 certificate SHA-1 digest: 61685b451876ee0479c07404596f254e387445ac
Signer #1 certificate MD5 digest: 7d98066ad427748b7fba20e238ad5f21
```

> [!Note]  
> You can download `apksigner` from here: https://developer.android.com/studio/index.html#command-line-tools-only

Also see: https://safenotes.dev/faqs.html
