### ISSUE TITLE
F-droid?

### ISSUE THREAD

**Issue by steadfasterX** [keshav-space/safenotes#2]
Link to FDroid is dead and seems its not in FDroid listed (or I'm blind 🤔 )

**Comment by keshav-space** [comment]
@steadfasterX we don't have a release for F-droid yet. Hopefully, we can have it soon.

**Comment by keshav-space** [comment]
Track F-Droid listing here: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11763

**Comment by keshav-space** [comment]
`Safe Notes` is live on f-droid: https://f-droid.org/en/packages/com.trisven.safenotes/

The icon missing on f-droid website will be fixed in the upcoming release.

</br>

> Putting these links here for posterity
> - https://gitlab.com/fdroid/fdroiddata/-/issues/2784
> - https://gitlab.com/fdroid/fdroiddata/-/issues/2790
>
