### ISSUE TITLE
single column list of notes

### ISSUE THREAD

**Issue by keshav-space** [keshav-space/safenotes#30]
let the user choose between list/tile view

**Comment by Julienjthomas** [comment]
Can i work on this?

**Comment by keshav-space** [comment]
Sure, if you need any help do let me know.

**Comment by Julienjthomas** [comment]
can u give a rough sketch of list tile?

**Comment by keshav-space** [comment]
if you look in `lib/views/home.dart` you will see this `_buildNotes` Widget 
```dart
  Widget _buildNotes() {
    return StaggeredGridView.countBuilder(
      padding: EdgeInsets.all(8),
      itemCount: notes.length,
      staggeredTileBuilder: (index) => StaggeredTile.fit(2),
      crossAxisCount: 4,
      mainAxisSpacing: 4,
      crossAxisSpacing: 4,
      itemBuilder: (context, index) {
        final note = notes[index];

        return GestureDetector(
          onTap: () async {
            await Navigator.pushNamed(
              context,
              '/viewnote',
              arguments: note,
            );
            _refreshNotes();
          },
          child: NoteCardWidget(note: note, index: index),
        );
      },
    );
  }
```
As of now, you would need to implement something similar to this say `_buildNotesTile`
for that, you will also need to implement `NoteTileWidget` similar to `NoteCardWidget`.

No need to worry about the selector button we will do that later. Get the ball rolling and we can always improve on it.

**Comment by Julienjthomas** [comment]
So what all things do you need in the listtile ?

**Comment by Julienjthomas** [comment]
![image](https://user-images.githubusercontent.com/40515690/195078399-f0708e7f-1964-421f-8034-6f9248ad914b.png)
is this enough @keshav-space

**Comment by keshav-space** [comment]
> So what all things do you need in the list tile?

```
Title [substring up to 30 characters]
Date [  yMMMd format ]
Description [substring up to 90 characters]
```

**Comment by Julienjthomas** [comment]
![image](https://user-images.githubusercontent.com/40515690/195081498-a730e538-3246-43ec-991e-e019bcfcb2e0.png)

**Comment by keshav-space** [comment]
This is awesome @Julienjthomas

**Comment by Julienjthomas** [comment]
So now we need a switch button to toggle between tile view and card view? right?

**Comment by keshav-space** [comment]
> So now we need a switch button to toggle between tile view and card view? right?

IMO it would be nice to split this into 2 different PR

- the first one that simply implements the logic for list title view
- second one to handle the logic for switching between the list and card view and persisting those changes

is that good for you?

**Comment by Julienjthomas** [comment]
Ok

**Comment by Julienjthomas** [comment]
So i will raise the pr
