### ISSUE TITLE
Merge Automatic Backup and Manual Export into one "Backup Notes" Setting

### ISSUE THREAD

**Issue by landry314** [keshav-space/safenotes#60]
Both Automatic Backup and Manual Export are setting sections to make backup files for your notes so why are they two rows in settings? It is a bit awkward. It is also awkward you use the word "export" instead of "backup". You are referring to exporting a backup file, of course, but the key word and more universally understood word is backup, not export.

Why not create one setting called "Backup Notes" and then within that have a manual backup file creating option and an automatic backup feature in the same place.

This also makes sense because right now you have two places to choose the path to the backup folder which is the same function. You can click on "Manual Export" and a Destination Folder dialog pops up where you chose a folder to place the file in or you can click on "Auto Backup" then choose a folder there to set it as a default. In there you also have a "Backup Now" option so you are really able to do everything inside of the Auto Backup section anyway.

I would rename "Auto Backup" to "Backup Notes" and eliminate "Manual Export" then within Backup Notes have a feature "Choose Backup Folder" and another "Backup Now" and another for "Auto Backup" which when turned on triggers an immediate Backup Now then remains on as it does so now. To create the feature of backing up to another folder which is NOT the default backup folder, you can also have "Manual Export" inside of the Backup Notes section but change the name because "Backup Now" is also a "manual" process. Only "Auto Backup" is not "manual".

Here is the hierarchy, naming, and order I suggest:

__Backup Notes__
1. Choose Default Backup Folder
2. Auto Backup
3. Force Backup Now
4. Manual Backup to Chosen Destination

Something like this. Let's discuss...

**Comment by keshav-space** [comment]
This is a great suggestion.
To be honest I was a bit confused about what to name the manual backup the only thing I could come up with at that time was `Manual Export`.  This is meant to be a redundant mechanism for data backup in the unlikely event that automatic backup breaks down as it has too many moving parts. 

Don't you think `Choose Default Backup Folder` is too long for button?

**Comment by landry314** [comment]
drop the word choose then? "Default Backup Folder"

**Comment by keshav-space** [comment]
> Drop the word choose then? "Default Backup Folder"

Yeah, that's much better

> do we need that function at all?

As I mentioned earlier, `4th one is meant to be a redundant mechanism for data backup in the unlikely event that automatic backup breaks down as it has too many moving parts.`

**Comment by landry314** [comment]
How about "Backup to a Different Folder"?

Setting name: "Backup Notes"

1.      Default Backup Folder
2.     Auto Backup
3.     Force Backup Now
4.     Backup to a Different Folder

**Comment by keshav-space** [comment]
This sounds good :)

**Comment by landry314** [comment]
Playing with the manual export feature, I realize is is just setting the backup folder then saving a file one time. It isn't just saving to different folder one time. Therefore is is redundant with features 1+3 above. I am not sure that is the intent.

**Comment by keshav-space** [comment]
> Therefore is redundant with features 1+3 above. I am not sure that is the intent.

Going forward Manual export will have 2 buttons 

1. Choose folder
2. Save to Download ( similar to v1.0 )

That way we can be sure that even if for some reason the folder picking is not working for some sdk user can still export data.

> Right now it is just like clicking on "Change Folder" then "Backup Now" which is kinda why I found it redundant before. To have real value it must backup to a folder without setting it as the new default.

Manual export will never change the existing backup routine or backup destination



> Ah, I just realized the naming of this file is different. I just suggested a naming scheme in issue #66 where you always put the date on it. I think that the date is important info to always have on the name.

Date & time is already included in manual export.

**Comment by landry314** [comment]
in version 2.1.0 in the backup section it says "choose backup folder from below" but there is nothing to choose anymore.

**Comment by keshav-space** [comment]
> in version 2.1.0 in the backup section it says "choose backup folder from below" but there is nothing to choose anymore.

Ouch! Will take care of it in the next update ;)
