### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by SebiTalent04** [keshav-space/safenotes#64]
**Is your feature request related to a problem? Please describe.**
Is there a way to translate the strings? I'd love to translate the app in Romanian.

**Describe the solution you'd like**
Add a translation ghide or something for contribuitors.

**Describe alternatives you've considered**

**Additional context**

**Comment by keshav-space** [comment]
Thanks @SebiTalent04, I will do the initial setup to support translation and then you can do string translation in a JSON file.
Will ping you once it's done. 
Hopefully, it will take a day or two at max.

**Comment by ghoevil** [comment]
@keshav-space I can translate it to chinese,pls ping me!

**Comment by keshav-space** [comment]
> I can translate it to chinese,pls ping me!

Thanks @ghoevil, will ping you too.

**Comment by keshav-space** [comment]
ping @SebiTalent04 and @ghoevil 
I have done the initial setup to support multiple languages 

@SebiTalent04 to support Romanian just create a `ro.json` file inside `assets/translation` and copy and paste all the keys from the [en-US.json](https://github.com/keshav-space/safenotes/blob/08d083f6feb9f4f10327ac0f1f9340737779b3e9/assets/translations/en-US.json) and replace the value with an equivalent Romanian translation

@ghoevil similarly to support Chinese just create a `zh-CN.json` file inside `assets/translation` and copy and paste all the keys from the [en-US.json](https://github.com/keshav-space/safenotes/blob/08d083f6feb9f4f10327ac0f1f9340737779b3e9/assets/translations/en-US.json) and replace the value with an equivalent Chinese translation

Ping me if you guys have any questions.

Note: anything inside `{}` should be kept as it is.

**Comment by keshav-space** [comment]
Closing this, @SebiTalent04. If you still wish to add a translation in Romanian, head over to this link: https://hosted.weblate.org/projects/safe-notes/.
