### ISSUE TITLE
[BUG] Weblate locked

### ISSUE THREAD

**Issue by comradekingu** [keshav-space/safenotes#89]
Some strange merge conflict in Weblate

https://hosted.weblate.org/projects/safe-notes/safe-notes-app/#alerts Rebasing (1/1)error: could not apply ad81a72... set locale for timeagoResolve all conflicts manually, mark them as resolved with"git add/rm <conflicted_files>", then run "git rebase --continue".You can instead skip this commit: run "git rebase --skip".To abort and get back to the state before "git rebase", run "git rebase --abort".Could not apply ad81a72... set locale for timeagoAuto-merging README.mdCONFLICT (content): Merge conflict in README.md(1)

Why a conflict in the README would arise I have no idea about, nor how it declares a locale, but
if you add "kingu" in https://hosted.weblate.org/access/safe-notes/#users I can have a look.
Is it set to look for new components?

**Comment by keshav-space** [comment]
@comradekingu Issue is now resolved
